on:
  push:
    branches:
      - main
name: NPM Publish
permissions:
  id-token: write  # Required for OIDC
  contents: read
jobs:
  publish:
    env:
      ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM Registry
        timeout-minutes: 10

        run: |
          echo "Creating git tag"
          PACKAGE_VERSION=$(cat package.json|grep version|head -1|awk -F: '{ print $2 }'|sed 's/[", ]//g')

          git remote set-url --push origin https://${GITHUB_ACTOR}:${ACTION_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git tag ${PACKAGE_VERSION}
          git push --tags

          echo "Publishing Tag to NPM Registry"
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          npm ci
          npm publish --access public
